version: "0.2"
ignorePaths:
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - bodyparser
  - langchain
  - npmmirror
  - npmrc
  - supabase
  - vitepress
ignoreWords:
  - trivago
  - zhengxs
